#!/usr/bin/env bash
test -z $(type -p) || { echo bash required; exit 1; }
set -e
set -u
source ${RRCONFINC}

apt=${APT:-/usr/bin/apt-get}
test -x $apt || {
  apt=/usr/bin/apt
  test -x $apt || {
    log Missing apt or apt-get binary
    exit 1
  }
}

sudo=
test x${USER} = "xroot" ||
  sudo=sudo

test $# -ge 1 || {
  log Missing action
  exit 1
}

action=install
case "=$1" in
=install)
  shift
  ;;
=remove)
  action=remove
  shift
  ;;
esac

export DEBIAN_FRONTEND=noninteractive
exec $sudo $apt $action -y --no-install-recommends $*
