#!/usr/bin/env bash
test -z $(type -p) || { echo bash required; exit 1; }
set -e
set -u
source ${RRCONFINC}

tmpdir=${XDG_RUNTIME_DIR:-/run/user/$(id -u)}

apt=${APT:-/usr/bin/apt-get}
test -x $apt || {
  apt=/usr/bin/apt
  test -x $apt || {
    log Missing apt or apt-get binary
    exit 1
  }
}

sudo=
test x${USER} = "xroot" ||
  sudo=sudo

test $# -ge 1 || {
  log Missing action
  exit 1
}

doUpdate() {
  cd $tmpdir
  touch --date="$(date -d 4+hours+ago)" lastupdate-stamp
  test lastupdate -nt lastupdate-stamp && {
    rm lastupdate-stamp
    exit 0
  }
  touch lastupdate
  exec $sudo $apt update
}

action=install
case "=$1" in
=install)
  shift
  test -f /var/lib/dpkg/info/$1.list && exit 0
  ;;
=remove)
  action=remove
  shift
  ;;
=update)
  doUpdate
  exit 0
  ;;  
esac

export DEBIAN_FRONTEND=noninteractive
exec $sudo $apt $action -y --no-install-recommends $*
